title: Jason Ballard Website
description: >- # this means to ignore newlines until "baseurl:"
  This site is an attempt to build a website using GitHub pages
# Site settings
baseurl: "https://jbtallgrass.github.io/cintel-01-pages/" # the subpath of your site, e.g. /blog
url: "https://jbtallgrass.github.io/" # the base hostname & protocol for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Optional settings
author: Jason Ballard
email: ballardjasona@gmail.comom
twitter_username:
github_username: JBtallgrass

